Repository gradle/develocity-bamboo-plugin, pull requests merged in 2023-03, with the labels that each got.

#4 Add documentation category in release notes
  .github/release-drafter.yml
Labels: documentation

#3 Remove redundant description in readme
  README.adoc
Labels: documentation

#5 Upgrade embedded maven extension version
  README.adoc
  pom.xml
  src/test/java/com/gradle/enterprise/bamboo/MavenEmbeddedResourcesTest.java
Labels: dependencies

#2 Bump up playwright version
  pom.xml
  src/test/java/it/com/gradle/enterprise/bamboo/BrowserTest.java
Labels: dependencies

#8 Bump org.apache.maven.plugins.maven-wrapper-plugin from 3.1.1 to 3.2.0
  .mvn/wrapper/maven-wrapper.jar
  .mvn/wrapper/maven-wrapper.properties
  mvnw
  mvnw.cmd
  pom.xml
Labels: dependencies

#17 Update gradle enterprise maven extension and tweak the documentation
  README.adoc
  pom.xml
  src/test/java/com/gradle/enterprise/bamboo/MavenEmbeddedResourcesTest.java
Labels: documentation, dependencies

#18 Bump com.microsoft.playwright.playwright from 1.31.0 to 1.32.0
  pom.xml
Labels: dependencies

#19 Add note about marketplace availability
  README.adoc
Labels: documentation
