Repository gradle/develocity-bamboo-plugin, pull requests merged in 2023-07, with the labels that each got.

#46 Bump CCUD Maven extension to 1.12.1
  pom.xml
  src/test/java/com/gradle/enterprise/bamboo/MavenEmbeddedResourcesTest.java
Labels: dependencies

#47 Documentation improvements
  .mvn/wrapper/maven-wrapper.properties
  README.adoc
  images/gradle-autoinjection-configuration.png
  images/gradle-maven-autoinjection-configuration.png
  images/maven-autoinjection-configuration.png
  images/no-autoinjection-configuration.png
  pom.xml
  src/main/i18n/gradle-enterprise-bamboo-plugin.properties
  src/test/java/com/gradle/enterprise/bamboo/BambooApi.java
  src/test/java/com/gradle/enterprise/bamboo/MavenEmbeddedResourcesTest.java
Labels: documentation

#50 Download bamboo agent from the atlassian repository
  src/test/java/com/gradle/enterprise/bamboo/BambooApi.java
Labels: tests

#51 Bump com.gradle.gradle-enterprise-maven-extension from 1.17.4 to 1.18
  README.adoc
  pom.xml
  src/test/java/com/gradle/enterprise/bamboo/MavenEmbeddedResourcesTest.java
Labels: dependencies

#52 Add a help text with the instructions for auto-injection
  images/gradle-autoinjection-configuration.png
  images/gradle-maven-autoinjection-configuration.png
  images/maven-autoinjection-configuration.png
  images/no-autoinjection-configuration.png
  pom.xml
  src/main/i18n/gradle-enterprise-bamboo-plugin.properties
  src/main/resources/templates/views/admin/buildScansConfig.ftl
  src/test/java/it/com/gradle/enterprise/bamboo/BuildScansConfigurationForm.java
  src/test/resources/generated-test-resources-923.zip
Labels: documentation

#53 Bump com.gradle.common-custom-user-data-maven-extension from 1.12.1 to 1.12.2
  pom.xml
  src/test/java/com/gradle/enterprise/bamboo/MavenEmbeddedResourcesTest.java
Labels: dependencies

#55 Set `gradle.enterprise.externally-applied` before applying GE plugin
  src/main/resources/gradle-enterprise/gradle/gradle-enterprise-init-script.gradle
Labels: enhancement

#57 Update Gradle Enterprise Maven extension to 1.18.1
  README.adoc
  pom.xml
  src/test/java/com/gradle/enterprise/bamboo/MavenEmbeddedResourcesTest.java
Labels: dependencies
