Repository gradle/develocity-bamboo-plugin, pull requests merged in 2024-04, with the labels that each got.

#127 Allow configuring credentials for gradle plugin repository
  src/main/i18n/develocity-bamboo-plugin.properties
  src/main/java/com/gradle/develocity/bamboo/GradleBuildScanInjector.java
  src/main/java/com/gradle/develocity/bamboo/admin/BuildScansConfigAction.java
  src/main/java/com/gradle/develocity/bamboo/config/GradleConfiguration.java
  src/main/java/com/gradle/develocity/bamboo/config/PersistentConfiguration.java
  src/main/java/com/gradle/develocity/bamboo/config/UsernameAndPasswordCredentialsProvider.java
  src/main/java/com/gradle/develocity/bamboo/utils/Objects.java
  src/main/resources/develocity/gradle/develocity-init-script.gradle
  src/main/resources/templates/views/admin/buildScansConfig.ftl
  src/test/java/com/gradle/develocity/bamboo/DevelocityPreJobActionTest.java
  src/test/java/com/gradle/develocity/bamboo/config/ConfigurationMigratorTest.java
  src/test/java/com/gradle/develocity/bamboo/config/JsonConfigurationConverterTest.java
  src/test/java/it/com/gradle/develocity/bamboo/BrowserTest.java
  src/test/java/it/com/gradle/develocity/bamboo/BuildScansConfigurationForm.java
  src/test/java/it/com/gradle/develocity/bamboo/browser/PluginConfigurationBrowserTest.java
Labels: enhancement

#130 Add VCS repo filtering
  pom.xml
  src/main/i18n/develocity-bamboo-plugin.properties
  src/main/java/com/gradle/develocity/bamboo/DevelocityPreBuildAction.java
  src/main/java/com/gradle/develocity/bamboo/VcsRepositoryFilter.java
  src/main/java/com/gradle/develocity/bamboo/VcsRepositoryUtils.java
  src/main/java/com/gradle/develocity/bamboo/admin/BuildScansConfigAction.java
  src/main/java/com/gradle/develocity/bamboo/config/BuildToolConfiguration.java
  src/main/java/com/gradle/develocity/bamboo/config/GradleConfiguration.java
  src/main/java/com/gradle/develocity/bamboo/config/MavenConfiguration.java
  src/main/java/com/gradle/develocity/bamboo/config/PersistentConfiguration.java
  src/main/resources/develocity/gradle/develocity-init-script.gradle
  src/main/resources/templates/views/admin/buildScansConfig.ftl
  src/test/java/com/gradle/develocity/bamboo/DevelocityPreBuildActionTest.java
  src/test/java/com/gradle/develocity/bamboo/MavenEmbeddedResourcesTest.java
  src/test/java/com/gradle/develocity/bamboo/VcsRepositoryFilterTest.java
  src/test/java/com/gradle/develocity/bamboo/VcsRepositoryUtilsTest.java
  src/test/java/com/gradle/develocity/bamboo/config/ConfigurationMigratorTest.java
  src/test/java/com/gradle/develocity/bamboo/config/JsonConfigurationConverterTest.java
  src/test/java/it/com/gradle/develocity/bamboo/BuildScansConfigurationForm.java
  src/test/java/it/com/gradle/develocity/bamboo/injection/AbstractInjectionTest.java
  src/test/java/it/com/gradle/develocity/bamboo/injection/GradleInjectionTest.java
  src/test/java/it/com/gradle/develocity/bamboo/injection/MavenInjectionTest.java
Labels: enhancement

#132 Add support for capturing of file fingerprints
  src/main/i18n/develocity-bamboo-plugin.properties
  src/main/java/com/gradle/develocity/bamboo/GradleBuildScanInjector.java
  src/main/java/com/gradle/develocity/bamboo/MavenBuildScanInjector.java
  src/main/java/com/gradle/develocity/bamboo/SystemProperty.java
  src/main/java/com/gradle/develocity/bamboo/admin/BuildScansConfigAction.java
  src/main/java/com/gradle/develocity/bamboo/config/BuildToolConfiguration.java
  src/main/java/com/gradle/develocity/bamboo/config/GradleConfiguration.java
  src/main/java/com/gradle/develocity/bamboo/config/MavenConfiguration.java
  src/main/java/com/gradle/develocity/bamboo/config/PersistentConfiguration.java
  src/main/resources/develocity/gradle/develocity-init-script.gradle
  src/main/resources/templates/views/admin/buildScansConfig.ftl
  src/test/java/com/gradle/develocity/bamboo/config/ConfigurationMigratorTest.java
  src/test/java/com/gradle/develocity/bamboo/config/JsonConfigurationConverterTest.java
  src/test/java/it/com/gradle/develocity/bamboo/BuildScansConfigurationForm.java
  src/test/java/it/com/gradle/develocity/bamboo/browser/PluginConfigurationBrowserTest.java
  src/test/java/it/com/gradle/develocity/bamboo/injection/GradleInjectionTest.java
  src/test/java/it/com/gradle/develocity/bamboo/injection/MavenInjectionTest.java
Labels: enhancement

#133 Bump com.gradle:common-custom-user-data-maven-extension from 1.13 to 2.0
  pom.xml
  src/test/java/com/gradle/develocity/bamboo/MavenEmbeddedResourcesTest.java
Labels: dependencies

#137 Fix develocity deprecations triggered by init-scripts
  src/main/resources/develocity/gradle/develocity-init-script.gradle
  src/test/java/it/com/gradle/develocity/bamboo/injection/GradleInjectionTest.java
Labels: enhancement

#139 Bump com.gradle:develocity-maven-extension from 1.21 to 1.21.1
  pom.xml
  src/test/java/com/gradle/develocity/bamboo/MavenEmbeddedResourcesTest.java
Labels: dependencies

#138 Add support for short-lived tokens
  pom.xml
  src/main/i18n/develocity-bamboo-plugin.properties
  src/main/java/com/gradle/develocity/bamboo/DevelocityAccessCredential.java
  src/main/java/com/gradle/develocity/bamboo/DevelocityPreJobAction.java
  src/main/java/com/gradle/develocity/bamboo/ShortLivedTokenClient.java
  src/main/java/com/gradle/develocity/bamboo/admin/AccessKeyValidator.java
  src/main/java/com/gradle/develocity/bamboo/admin/BuildScansConfigAction.java
  src/main/java/com/gradle/develocity/bamboo/config/PersistentConfiguration.java
  src/main/resources/templates/views/admin/buildScansConfig.ftl
  src/test/java/com/gradle/develocity/bamboo/DevelocityAccessCredentialTest.java
  src/test/java/com/gradle/develocity/bamboo/DevelocityPreJobActionTest.java
  src/test/java/com/gradle/develocity/bamboo/TestFixtures.java
  src/test/java/com/gradle/develocity/bamboo/config/ConfigurationMigratorTest.java
  src/test/java/com/gradle/develocity/bamboo/config/JsonConfigurationConverterTest.java
  src/test/java/it/com/gradle/develocity/bamboo/BuildScansConfigurationForm.java
  src/test/java/it/com/gradle/develocity/bamboo/MockDevelocityServer.java
  src/test/java/it/com/gradle/develocity/bamboo/ShortLivedTokenClientTest.java
  src/test/java/it/com/gradle/develocity/bamboo/browser/PluginConfigurationBrowserTest.java
  src/test/java/it/com/gradle/develocity/bamboo/injection/GradleInjectionTest.java
Labels: enhancement

#143 Translate all access keys to short-lived tokens
  src/main/java/com/gradle/develocity/bamboo/DevelocityAccessCredential.java
  src/main/java/com/gradle/develocity/bamboo/DevelocityAccessCredentials.java
  src/main/java/com/gradle/develocity/bamboo/DevelocityPreJobAction.java
  src/main/java/com/gradle/develocity/bamboo/ShortLivedTokenClient.java
  src/main/java/com/gradle/develocity/bamboo/admin/BuildScansConfigAction.java
  src/test/java/com/gradle/develocity/bamboo/DevelocityAccessCredentialsTest.java
  src/test/java/com/gradle/develocity/bamboo/DevelocityPreJobActionTest.java
  src/test/java/it/com/gradle/develocity/bamboo/ShortLivedTokenClientTest.java
Labels: enhancement

#148 Fix build scan link log parsing for multiple tasks
  pom.xml
  src/main/java/com/gradle/develocity/bamboo/AbstractBuildScanInjector.java
  src/test/java/it/com/gradle/develocity/bamboo/injection/GradleInjectionTest.java
  src/test/resources/generated-test-resources-923.zip
  src/test/resources/generated-test-resources-9_2_13.zip
Labels: bug
