Repository gradle/develocity-bamboo-plugin, pull requests merged in 2025-05, with the labels that each got.

#274 Bump com.gradle:common-custom-user-data-maven-extension from 2.0.1 to 2.0.2
  README.adoc
  pom.xml
  src/test/java/com/gradle/develocity/bamboo/MavenEmbeddedResourcesTest.java
Labels: dependencies

#275 Create short-lived tokens if Develocity injection is disabled
  src/main/i18n/develocity-bamboo-plugin.properties
  src/main/java/com/gradle/develocity/bamboo/DevelocityPreJobAction.java
  src/main/java/com/gradle/develocity/bamboo/ShortLivedTokenClient.java
  src/main/resources/templates/views/admin/buildScansConfig.ftl
  src/test/java/com/gradle/develocity/bamboo/DevelocityPreJobActionTest.java
Labels: enhancement

#278 Take into account allowUntrusted when changed at runtime
  src/main/java/com/gradle/develocity/bamboo/DevelocityPreJobAction.java
  src/main/java/com/gradle/develocity/bamboo/ShortLivedTokenClient.java
  src/main/java/com/gradle/develocity/bamboo/ShortLivedTokenClientFactory.java
  src/test/java/com/gradle/develocity/bamboo/DevelocityPreJobActionTest.java
  src/test/java/it/com/gradle/develocity/bamboo/ShortLivedTokenClientTest.java
Labels: bug
